
export const GameActions  = {
    LEFT_PRESS_ACTION : "LEFT_PRESS_ACTION",
    RIGHT_PRESS_ACTION : "RIGHT_PRESS_ACTION",
    TOP_PRESS_ACTION : "TOP_PRESS_ACTION",
    BOTTOM_PRESS_ACTION : "BOTTOM_PRESS_ACTION",
    NOTHING_PRESS_ACTION : "NOTHING_PRESS_ACTION",
    PAUSE_ACTION : "PAUSE_ACTION" 
}